In [387]:
import pandas as pd
import numpy as np

In [388]:
df = pd.read_csv('netflix.csv', index_col=0)

In [389]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,+14,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,+18,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,+18,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [390]:
df.shape

(8807, 12)

In [391]:
df2 = df.copy()

  > Sacamos los directores por separado

In [392]:
def separar (col):
    try:
        return col.split(',')
    except:
        pass

In [393]:
df['director'] = df['director'].apply(separar)

In [394]:
df = df.explode('director')

In [395]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,+14,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,+18,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,NaN,NaN,"September 24, 2021",2021,+18,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [396]:
list(df['director'].unique())

['Kirsten Johnson',
 None,
 'Julien Leclercq',
 'Mike Flanagan',
 'Robert Cullen',
 ' José Luis Ucha',
 'Haile Gerima',
 'Andy Devonshire',
 'Theodore Melfi',
 'Kongkiat Komesiri',
 'Christian Schwochow',
 'Bruno Garotti',
 'Pedro de Echave García',
 ' Pablo Azorín Williams',
 'Adam Salky',
 'Olivier Megaton',
 'K.S. Ravikumar',
 'Alex Woo',
 ' Stanley Moore',
 'S. Shankar',
 'Rajiv Menon',
 'Dennis Dugan',
 'Scott Stewart',
 'Robert Luketic',
 'Ashwiny Iyer Tiwari',
 ' Abhishek Chaubey',
 ' Saket Chaudhary',
 'Daniel Sandu',
 'Cédric Jimenez',
 'George Nolfi',
 'Steven Spielberg',
 'Jeannot Szwarc',
 'Joe Alves',
 'Joseph Sargent',
 'Tyler Greco',
 'Daniel Espinosa',
 'Bunmi Ajakaiye',
 'Antoine Fuqua',
 'Toshiya Shinohara',
 'Masahiko Murata',
 'Hajime Kamegaki',
 'Hirotsugu Kawasaki',
 'Toshiyuki Tsuru',
 'Tensai Okamura',
 'David Yarovesky',
 'Hanns-Bruno Kammertöns',
 ' Vanessa Nöcker',
 ' Michael Wech',
 'David A. Vargas',
 'Kemi Adetiba',
 'Ben Simms',
 'Prakash Satam',
 'Delhiprasad Deenadayalan',
 'Tomer Eshed',
 'Cedric Nicolas-Troyan',
 'JJC Skillz',
 ' Funke Akindele',
 'Thomas Sieben',
 'Marcus Clarke',
 'Alice Waddington',
 'Mona Achache',
 ' Patricia Tourancheau',
 'Alexis Almström',
 'Raja Gosnell',
 'Stephen Kijak',
 'Chapman Way',
 ' Maclain Way',
 'Jason Hehir',
 'Yemi Amodu',
 'Lijo Jose Pellissery',
 'David de Vos',
 'Luis Alfaro',
 ' Javier Gómez Santander',
 'Sara Colangelo',
 'Stephen Herek',
 'Rahul Rawail',
 'Jane Campion',
 'Nagesh Kukunoor',
 'Luke Holland',
 'Shanker Raman',
 'JP Habac',
 'Vidhu Vinod Chopra',
 'Mark Rosman',
 'Gilles Paquet-Brenner',
 'Lasse Hallström',
 'Scott Pleydell-Pearce',
 'Ridley Scott',
 'Neill Blomkamp',
 'Phillip Noyce',
 'Renny Harlin',
 'Anthony Minghella',
 'Simon Wincer',
 'Spike Lee',
 'Sebastián Schindel',
 'Steven C. Miller',
 'Richard LaGravenese',
 'Martin Campbell',
 'Reginald Hudlin',
 'George Jackson',
 ' Doug McHenry',
 'Eric Meza',
 'Gerhard Mostert',
 'Michael Martin',
 'Michael Rymer',
 'Andrew Lau Wai-keung',
 ' Alan Mak',
 'Brett Weiner',
 'Jim Henson',
 'Gary Winick',
 'Danishka Esterhazy',
 'Troy Byer',
 'Pang Ho-cheung',
 'Tim Burton',
 'David Zucker',
 'Kinka Usher',
 'Sergio Leone',
 "Matthew O'Callaghan",
 ' Todd Wilderman',
 'Bobby Farrelly',
 ' Peter Farrelly',
 'Wolfgang Petersen',
 'Peter Spirer',
 'Michael Carney',
 'Richard Linklater',
 'Amy Rice',
 'Randal Kleiser',
 'Michael Ritchie',
 'J. Lee Thompson',
 'Evan Goldberg',
 ' Seth Rogen',
 'Tom Shadyac',
 'Peter Segal',
 'Malcolm D. Lee',
 'Ramzy Bedia',
 ' Éric Judor',
 'Sharan Koppisetty',
 'Taylor Sheridan',
 'Sachin Yardi',
 'Saurabh Kabra',
 'Mark Waters',
 'Partho Mitra',
 'Santram Varma',
 'Anil V. Kumar',
 ' Anurag Basu',
 'Sangeeth Sivan',
 'Umesh Ghadge',
 'David Dhawan',
 'Dibakar Banerjee',
 'Apoorva Lakhia',
 'Milan Luthria',
 'Pawan Kripalani',
 'Bhushan Patel',
 'Magnus Martens',
 'Raj Nidimoru',
 ' Krishna D.K.',
 'Joshua Rofé',
 'Brad Anderson',
 'Mauricio Dias',
 ' Tatiana Villela',
 'Angel Kristi Williams',
 'Roger Donaldson',
 'Christopher Alender',
 'Rush Sturges',
 'David Oyelowo',
 'Mark Lo',
 'Crystal Moselle',
 'Rathindran R Prasad',
 'Han Kwang Il',
 'Karim El Shenawy',
 'Yin Chen-hao',
 'Brian Andrew Mendoza',
 'Dave Needham',
 'Veronica Velasco',
 'Drake Doremus',
 'Miguel Alexandre',
 'Mani Ratnam',
 'Michael Harte',
 'Tosin Igho',
 'Alice Filippi',
 'Paakhi Tyrewala',
 'Laura Brownson',
 'Steve Brill',
 'Moses Inwang',
 'Ferdinando Cito Filomarino',
 'Juan Carlos Medina',
 'Inma Torrente',
 'Julián Gaviria',
 'Steven Yamamoto',
 'Charles Uwagbai',
 'Julián Hernández',
 'Sam Hobkinson',
 'Vince Marcello',
 'Jonathan Teplitzky',
 'Sakon Tiacharoen',
 'Floyd Russ',
 'Dustin Hoffman',
 'Adze Ugah',
 'Hideaki Takizawa',
 'Quoc Bao Tran',
 'Bejoy Nambiar',
 ' Priyadarshan',
 ' Karthik Narain',
 ' Vasanth Sai',
 ' Karthik Subbaraj',
 ' Arvind Swamy',
 ' Rathindran R Prasad',
 ' Sarjun',
 ' Gautham Vasudev Menon',
 'Kayode Kasum',
 'Just Philippot',
 'Kirk DeMicco',
 ' Brandon Jeffords',
 'Rohit Shetty',
 'Cavi Borges',
 ' Luciano Vidigal',
 'Alejandro Doria',
 'Laura Fairrie',
 'Marcelo Piñeyro',
 'Izu Ojukwu',
 'Peter Winther',
 'Susan Lacy',
 'Billy Corben',
 'James Mangold',
 'Chineze Anyaene',
 'Hsu Fu-chun',
 'Kristine Stolakis',
 'Eva Müller',
 ' Michael Schmitt',
 'Brian Levant',
 'Rod Daniel',
 'Robert Zemeckis',
 'Todor Chapkanov',
 'Phil Lord',
 ' Christopher Miller',
 'John Hughes',
 'Justin Baldoni',
 'Joe Roth',
 'Mark Helfrich',
 'Mag Hsu',
 ' Hsu Chih-yen',
 'Christopher Nolan',
 'Paul Thomas Anderson',
 'Nick Castle',
 'Howard Zieff',
 'David Feiss',
 'David Gordon Green',
 'Jorge Blanco',
 'Zara Hayes',
 'Gary Ross',
 'Clint Eastwood',
 'Trey Parker',
 'Kelly Fremon Craig',
 'Tom Elkins',
 'Tony Scott',
 'Brad Furman',
 'Sylvain White',
 'Irwin Winkler',
 'Garry Marshall',
 'Kenneth Gyang',
 'Jaume Balagueró',
 'Najwa Najjar',
 'Selçuk Metin',
 'Keishi Otomo',
 'David Charhon',
 'Michelle Bello',
 'Steven Tsuchida',
 'Daniel Markowicz',
 'Louie Schwartzberg',
 'Glen Winter',
 'Ram Gopal Varma',
 'David Benullo',
 'Laxman Utekar',
 'Royale Watkins',
 ' Rich Schlansker',
 'Yuval Adler',
 'Quentin Tarantino',
 'Clay Glen',
 'Muzi Mthembu',
 'Marcos Bucay',
 'Peter Thorwarth',
 'Kim Seong-hun',
 'Augustine Frizzell',
 'Sidheswar Shukla',
 'Rajiv Chilaka',
 'Binayak Das',
 'Arpan Sarkar',
 ' Shyamal Chaulia',
 ' Owll Mina',
 'Ainsley Gardiner',
 ' Briar Grace-Smith',
 'Mahmoud Karim',
 'Kyohei Ishiguro',
 'Seyi Babatope',
 'Johane Matte',
 ' Andrew L. Schmidt',
 ' Francisco Ruiz Velasco',
 'Morgan Ingari',
 'Abdulaziz Alshlahei',
 'Edward Drake',
 'Kathryn Fasegha',
 'Sita Likitvanichkul',
 ' Jetarin Ratanaserikiat',
 ' Apirak Samudkitpaisan',
 ' Thanabodee Uawithya',
 ' Adirek Wattaleela',
 'Leigh Janiak',
 'Luis Estrada',
 'Garrett Bradley',
 'Sofia Coppola',
 'Colin Trevorrow',
 'Bill Condon',
 'David Slade',
 'Chris Weitz',
 'Catherine Hardwicke',
 'Hadrah Daeng Ratu',
 'Tommy Chong',
 'Fred Ouro Preto',
 'Mayye Zayed',
 'Alessandra de Rossi',
 'Ash Brannon',
 ' Chris Buck',
 'Alaa Eddine Aljem',
 'Tom Donahue',
 'Roberto De Feo',
 ' Paolo Strippoli',
 'Navot Papushado',
 'Manuel Alcalá',
 'Ricardo Trogi',
 'Semi Chellas',
 'Akay Mason',
 ' Abosi Ogba',
 'Viridiana Lieberman',
 'Nima Nourizadeh',
 'Daniel Růžička',
 'Juraj Šajmovič',
 'Femi D. Ogunsanwo',
 'Douglas Attal',
 'Kim Joo-hyung',
 'Avi Federgreen',
 'Jericca Cleland',
 ' Kevin Munroe',
 'Ahmed Siddiqui',
 'Hallie Meyers-Shyer',
 'Scott Speer',
 'Barry Levinson',
 'Tolulope Itegboje',
 'Camille Delamarre',
 'Pascal Atuma',
 'Oleg Trofim',
 'Mahmood Ali-Balogun',
 'Jan Holoubek',
 'Anurin Nwunembom',
 ' Musing Derrick',
 'Christine Luby',
 'Udoka Oyeka',
 'Yeo Siew Hua',
 'Hardik Mehta',
 'Rajveer Singh Maan',
 ' Harpeet Singh',
 'Youssef Chahine',
 'Saw Teong Hin',
 ' Nik Amir Mustapha',
 ' M.S. Prem Nath',
 'Rano Karno',
 'Pramod Pawar',
 'Naresh Saigal',
 'Vinil Mathew',
 'Neri Parenti',
 'Ramsey Nouah',
 'Bong Joon Ho',
 'Kim Tae-hyung',
 'Michael Spierig',
 ' Peter Spierig',
 'Ernie Barbarash',
 'Matt Ogens',
 'Jay Roach',
 'McG',
 'Frank Marshall',
 'Victor Vu',
 'Chow Hin Yeung Roy',
 'Joel Hopkins',
 'John Stevenson',
 ' Mark Osborne',
 'Jennifer Yuh Nelson',
 'Greg Berlanti',
 'Garth Davis',
 'Malik Nejer',
 'Rob Marshall',
 'Martin Brest',
 'Shuko Murase',
 'Paul W.S. Anderson',
 'Ivan Reitman',
 'Joel Gallen',
 'Claire McCarthy',
 'Mary Lambert',
 'Sidharta Tata',
 ' Aco Tenriyagelli',
 ' Dian Sastrowardoyo',
 ' Ifa Isfansyah',
 ' Jason Iskandar',
 'Trevor Nunn',
 'Gabriele Muccino',
 'Jim Field Smith',
 'Chris Koch',
 'J.J. Abrams',
 'Rob Minkoff',
 'Lynn Shelton',
 'Adam McKay',
 'Anton Corbijn',
 'Robin Bissell',
 'David Fincher',
 'John G. Avildsen',
 'Alan Parker',
 'Walter Hill',
 'Stephen Frears',
 'Bryan Bertino',
 'Phil Alden Robinson',
 'Florian Henckel von Donnersmarck',
 'Len Wiseman',
 'Måns Mårlind',
 ' Björn Stein',
 'Patrick Tatopoulos',
 'Robert O. Peters',
 'Vincent Ward',
 'Gregory Nava',
 'Mary Harron',
 'Matt Thompson',
 'Jameel Buari',
 'Shen Leping',
 'Matt Aselton',
 'Jose Javier Reyes',
 'Jakub Piątek',
 'John Dower',
 'B. T Thomas',
 'Andrew Dominik',
 'Nibal Arakji',
 'Sofie Šustková',
 'Anissa Bonnefont',
 'Bahij Hojeij',
 'Jonathan Hensleigh',
 'Srijit Mukherji',
 ' Vasan Bala',
 'Justin P. Lange',
 'Kimmy Gatewood',
 'Tània Balló',
 'Manolo Caro',
 'Jayme Monjardim',
 'Kingsley Ogoro',
 'Cristina Jacob',
 'Fernando Moro',
 'Ivan Andrew Payawal',
 'Yoshiyuki Tomino',
 ' Yoshikazu Yasuhiko',
 'Rob Seidenglanz',
 'Simon Frederick',
 'Michihito Fujii',
 'Paul Weitz',
 'Karthik Subbaraj',
 'Lucky Kuswandi',
 'Soudade Kaadan',
 'Antoinette Jadaone',
 'Marie Clements',
 'David O. Russell',
 'Achille Brice',
 'Max Jabs',
 'Sarawut Wichiensarn',
 'Ricardo de Montreuil',
 'Peter Chelsom',
 'Michael Lockshin',
 'Francine Parker',
 'Daniel Schechter',
 'Mike Gunther',
 'David Zeiger',
 'Michael Simon',
 'Jerry Rothwell',
 'Joe Berlinger',
 ' Bruce Sinofsky',
 'Ian Cheney',
 ' Sharon Shattuck',
 'Bradley Parker',
 'Prabhakaran',
 'Manjari Makijany',
 'Jay Oliva',
 'Chris Appelhans',
 'Michael Tiddes',
 'Lara Saba',
 'Bao Nhan',
 ' Namcito',
 'Mark Raso',
 'Tariq Alkazim',
 'Yulene Olaizola',
 'Matthew Heineman',
 'Robert Peters',
 'Jonathan Clay',
 'Ally Pankiw',
 'George Ford',
 'Lee Kae-byeok',
 'Jayan Moodley',
 'Daniel Benmayor',
 'Alex Díaz',
 'Helena Bergström',
 'Alejandro De Grazia',
 ' Juan Stadler',
 'Myriam Fares',
 'Chiaki Kon',
 'Rae Red',
 'Lance Hool',
 'Nicole Conn',
 'Les Mayfield',
 'Ellen Seidler',
 ' Megan Siler',
 'Roger Christian',
 'Peter Galison',
 'Lance Young',
 'Leandro Neri',
 'Thom Fitzgerald',
 'Don Michael Paul',
 'Andrzej Bartkowiak',
 'Harold Becker',
 'Andrew Jenks',
 'Ric Roman Waugh',
 'Rob Reiner',
 'Andy Tennant',
 'Tade Ogidan',
 'Scott Spiegel',
 'Jessie Nelson',
 'Theodore Witcher',
 'Aurora Guerrero',
 'Michael Jai White',
 'James McTeigue',
 'Takuya Igarashi',
 'Michelle MacLaren',
 'Hidenori Inoue',
 'Todd Phillips',
 'Steve Ball',
 'Dominic Sena',
 'Alan Alda',
 'Mika Kaurismäki',
 'Sydney Pollack',
 'Lorene Scafaria',
 'Barbra Streisand',
 'Michael Winterbottom',
 'Emma Tammi',
 'Peter Hutchings',
 'George Ratliff',
 'Bo Burnham',
 'Ekene Som Mekwunye',
 'David Frankel',
 'Kevin Johnson',
 'José Larraza',
 ' Marc Pons',
 'Gary Sing',
 'Julio Quintana',
 'Paween Purijitpanya',
 'Pablo Faro',
 'Letizia Lamartire',
 'Ray Jiang',
 'Daniel Vernon',
 'Steve Gukas',
 'Tim Johnson',
 'Vishwesh Krishnamoorthy',
 'Zack Snyder',
 'Uduak-Obong Patrick',
 'Mohamed Diab',
 'Amr Salama',
 'Christopher Amos',
 'Robert Rodriguez',
 'David Ayer',
 'Eshom Nelms',
 ' Ian Nelms',
 'James Moll',
 'James Redford',
 'Kaashvie Nair',
 'J.D. Dillard',
 'Nikhil Pherwani',
 'Mae Czarina Cruz',
 'Praveen Kandregula',
 'Cecilia Verheyden',
 'Daniel Minahan',
 'Donovan Marsh',
 'Brent Dawes',
 'Leli Maki',
 'Uzodinma Okpechi',
 'Daniel Prochaska',
 'Joe Wright',
 'Matthew Vaughn',
 'Aditya Kripalani',
 'Adriano Rudiman',
 'David Pablos',
 'Alexandre Aja',
 'Cai Cong',
 'Samuel Olatunji',
 'Ramon Térmens',
 'Svetlana Cvetko',
 'Martin Prakkat',
 'Baran bo Odar',
 'Zhang Chong',
 'Yılmaz Erdoğan',
 'Shantrelle P. Lewis',
 'Ivan Ayr',
 'Anthony Mandler',
 'Vijay Roche',
 "Stanley Menino D'Costa",
 'Jennifer Brea',
 'Julia von Heinz',
 'Niels Arden Oplev',
 'Don Argott',
 ' Sheena M. Joyce',
 'Joshua Zeman',
 'Duncan Skiles',
 'Sean McNamara',
 'Vondie Curtis-Hall',
 'Robert Radler',
 'Roel Reiné',
 'Dean Parisot',
 'Paul Greengrass',
 'Justin Kelly',
 'Eric Darnell',
 ' Tom McGrath',
 ' Conrad Vernon',
 'Suhas Kadav',
 'Jeff Wadlow',
 'Charles Martin',
 'Stella Corradi',
 'Roland Emmerich',
 'Kevin Macdonald',
 'Ann Deborah Fishman',
 'Chris Gorak',
 'Peter Jackson',
 'Roger Kumble',
 'Jonathan Lynn',
 'Courtney Hunt',
 'Pierre Greco',
 ' Nancy Florence Savard',
 'Andrew Davis',
 'Kevin Smith',
 'Chaitanya Tamhane',
 'Oriol Paulo',
 'Mike Rianda',
 ' Jeff Rowe',
 'Johannes Roberts',
 'Robert Pulcini',
 ' Shari Springer Berman',
 'Pedro Antonio',
 'John Wells',
 'Jonathan Liebesman',
 'Maria Pulera',
 'Santhosh Viswanath',
 'Seema Pahwa',
 'Ozan Açıktan',
 'Meltem Bozoflu',
 'Hakan Algül',
 'Selçuk Aydemir',
 ' Birkan Pusa',
 'Ömer Faruk Sorak',
 'Şenol Sönmez',
 'Alexis Morante',
 'Burak Aksak',
 'Kıvanç Baruönü',
 'Rindala Kodeih',
 'Kongkiat Khomsiri',
 'Bedran Güzel',
 'Marwan Nabil',
 'MIKIKO',
 ' Daito Manabe',
 ' Ömer Faruk Sorak',
 'Takashi Shimizu',
 'Joe Penna',
 'Ahishor Solomon',
 'Curtis Graham',
 'Gerardo Gatica',
 'Akshay Sanjeev Chavan',
 ' Sumit Das',
 'John Madden',
 'Edward James Olmos',
 'Abhinay Deo',
 'Kiran Rao',
 'Abbas Tyrewala',
 'Ashutosh Gowariker',
 'Satyajit Bhatkal',
 'Anusha Rizvi',
 ' Mahmood Farooqui',
 'Aamir Khan',
 'Shashank Khaitan',
 ' Raj Mehta',
 ' Neeraj Ghaywan',
 ' Kayoze Irani',
 'Ryan Crego',
 'Cassi Simonds',
 'Guillermo del Toro',
 'Tony Abulu',
 'Stefan Westerwelle',
 'Ron Howard',
 'Justin Benson',
 ' Aaron Moorhead',
 'Niki Caro',
 'Mark Dennis',
 ' Ben Foster',
 'Taranveer Singh',
 'TT The Artist',
 'Keiichi Sato',
 ' Yasushi Kawamura',
 'Glenn Weiss',
 'Michael Civille',
 'Ryuichi Hiroki',
 'One9',
 'Luis Valdez',
 'Cheng Wei-hao',
 'Pass Patthanakumjon',
 'Buchi Babu Sana',
 'Fredrick Munk',
 'Moyoung Jin',
 ' Caroline Sá',
 ' Deepti Kakkar',
 ' Fahad Mustafa',
 ' Hikaru Toda',
 ' Chico Pereira',
 ' Elaine McMillion Sheldon',
 'Zhao Ji',
 'Jamie Babbit',
 'Park Hoon-jung',
 'Dare Olaitan',
 'Ben Falcone',
 'Travon Free',
 ' Martin Desmond Roe',
 'Angga Dwimas Sasongko',
 'Steve Rolston',
 'Shalini Kantayya',
 'Madonne Ashwin',
 'Enah Johnscott',
 'Braden R. Duemmler',
 'Cal Brunker',
 'Steve Pink',
 'Xiao Feng',
 'Ricky Staub',
 'Patrick Durham',
 ' Paul G. Volk',
 'BB Sasore',
 'Naseef Yusuf Izuddin',
 'Appie Boudellah',
 ' Aram van de Rest',
 'Sylvie Verheyde',
 'Nick Moore',
 'Alex Zamm',
 'Rajkumar Hirani',
 'Rajesh Mapuskar',
 'Lina Al Abed',
 'James Wan',
 'David Hackl',
 'Takeshi Nozue',
 'Subhash Kapoor',
 'Ringo Lam',
 'George Cukor',
 'Tony Giglio',
 'Shinji Aramaki',
 ' Masaru Matsumoto',
 'John Luessenhop',
 'Hanung Bramantyo',
 ' Pandu Adjisurya',
 'Bashir El Deek',
 'Roman Polański',
 'Nelson McCormick',
 'Mic Rodgers',
 'Shawn Rech',
 'Peyton Reed',
 'Julian Schnabel',
 'Adrián García Bogliano',
 'Jose Gomez',
 'Jonathon Link',
 'Blair Simmons',
 'Justin Chadwick',
 'John Hillcoat',
 'Nadine Ibrahim',
 'Roman White',
 'Fermín Muguruza',
 'Mike Hodges',
 'Eylem Kaftan',
 'Fernando Ayllón',
 'Umesh Bist',
 'Massimiliano Camaiti',
 'Aleksey Tsitsilin',
 'Ali Tabrizi',
 'Kagiso Lediga',
 'Jung-ah Im',
 'Takuma Sato',
 'Brody Chu',
 'Dimitri Logothetis',
 'Taketoshi Sado',
 'Li Weiran',
 'Chinaza Onuzo',
 'Anna Elizabeth James',
 'Vitor Brandt',
 'Troy Miller',
 "Liam O'Donnell",
 'Manny Rodriguez',
 ' Jay Lavender',
 'Farah Nabulsi',
 'Walter Taylaur',
 'Chris Smith',
 'Alain Brunard',
 'Tate Taylor',
 'Ladislaus Kiraly',
 'Oliver Stone',
 'Hemambar Jasti',
 'Taylor Morden',
 'Helena Coan',
 'Muharrem Gülmez',
 'Dolapo Adeleke',
 'Mahsun Kırmızıgül',
 'Can Ulkay',
 'Luis Alejandro Pérez',
 'Ketche',
 'Erol Özlevi',
 'Miguel Arteta',
 'Tolga Örnek',
 'Pablo Agüero',
 'Mohammad Irfan Ramly',
 'Kevin McManus',
 ' Matthew McManus',
 'Ange Basterga',
 ' Nicolas Lopez',
 'Gitanjali Rao',
 'Halitha Shameem',
 'Carlos Moreno',
 'Maribel Sánchez-Maroto',
 'Fajar Bustomi',
 'Taylor Hackford',
 'Amy Poehler',
 'Jared Hess',
 ' Tyler Measom',
 'Mike Binder',
 'Abir Sengupta',
 'Sunny Lau',
 'Emmett Malloy',
 'Xavier Maingon',
 ' Marc-Antoine Hélard',
 'Milton Kremer',
 'Kevin Costner',
 'Marco Petry',
 'Andrew Duncan',
 ' Ken Cunningham',
 'Liam Lynch',
 'Jérémie Degruson',
 ' Ben Stassen',
 'Matt Ross',
 'Dani de la Orden',
 'Pablo Larraín',
 'John Erick Dowdle',
 'Jesse Peretz',
 'Ribhu Dasgupta',
 'Rizki Balki',
 'Shunsuke Kariyama',
 'Jeferson De',
 'Barry Avrich',
 'David Tryhorn',
 ' Ben Nicholas',
 'Tirumala Kishore',
 'Huang Hsin-Yao',
 'Saron Sakina',
 'J Blakeson',
 'Khalid Rahman',
 'Luis Ara',
 'Tharun Bhascker Dhaassyam',
 ' B. V. Nandini Reddy',
 ' Nag Ashwin',
 ' Sankalp Reddy',
 'Prateek Vats',
 'Alex Merkin',
 'Vikram Bhatt',
 'Dallas Jenkins',
 'Damián Romay',
 'Hamisha Daryani Ahuja',
 'Hong Khaou',
 'Mario Briongos',
 'Vinay Bharadwaj',
 'Michael Fimognari',
 'Eric D. Cabello Díaz',
 'Clara Martínez-Lázaro',
 'Monty Tiwa',
 'Ava DuVernay',
 'Alain Darborg',
 'Filip Zylber',
 'Julien Royal',
 'Brian Baugh',
 'Henri Wong',
 'Maïa Sandoz',
 'Mostofa Sarwar Farooki',
 'Joseph Hsu',
 'Sam Levinson',
 'Jo Sung-hee',
 'Michèle Ohayon',
 'Rocco Ricciardulli',
 'Guo Jingming',
 'Jan Belcl',
 'Esteban Crespo',
 'Noé González',
 'Sarah Gavron',
 'Martin Scorsese',
 'Richard Arellano',
 'Jon Favreau',
 'Marco Pontecorvo',
 'Gregory Plotkin',
 'Lluís Quílez',
 'Jude Weng',
 'Simon Stone',
 'Noviandra Santosa',
 'Jeremy Grant',
 'Jeo Baby',
 'Glendyn Ivin',
 'Okey Oku',
 'Ifeanyi Ikpoenyi',
 'Chris Eneng Enaji',
 'Ángeles Reiné',
 'Paul Haggis',
 'Ramin Bahrani',
 'Nicol Paone',
 'Nick Rowland',
 'RZA',
 'Cooper Karl',
 'Gary Fleder',
 'J.A. Bayona',
 'Darren Lynn Bousman',
 'Lydia Dean Pilcher',
 ' Ginny Mohler',
 "Cris D'Amato",
 'Mikael Håfström',
 ' Simon J. Smith',
 'Byeon Hee-sun',
 'Peter Facinelli',
 'Renuka Shahane',
 'Ross Kauffman',
 'Sung Do-jun',
 'Charles Gozali',
 ' Bagus Bramanti',
 'James Toback',
 'Tiller Russell',
 "Francisco D'Eufemia",
 'Chris Rock',
 'Juliet May',
 'Stanley Nelson',
 'Olivier Nakache',
 ' Éric Toledano',
 'Prakash Jha',
 'Rohan Sippy',
 'Ross Venokur',
 'Rohena Gera',
 'Maite Ruiz De Austri',
 'Jastis Arimba',
 'Eric Summer',
 ' Éric Warin',
 'Kornél Mundruczó',
 'Alejandro Ruax',
 ' Ramiro Martínez',
 'Florent Bodin',
 'Sohail Khan',
 'Hallvard Bræin',
 'Jeff Tremaine',
 'Christian Alvart',
 'Robert Townsend',
 'Jeff Deverett',
 'Ron Krauss',
 'Brian Robbins',
 'Jeff Stilson',
 'Sean Penn',
 'Mark McQueen',
 'Melanie Mayron',
 'Donald Petrie',
 'Tony Collingwood',
 'Jennifer Beamish',
 ' Toby Trackman',
 'Jaume Collet-Serra',
 'Kim Dong-kyu',
 'Shaz Bennett',
 'Samar Shaikh',
 'Archie Hekagery',
 'Sabrina Rochelle Kalangie',
 'Cosima Spender',
 'Liao Shih-han',
 'Arnon Manor',
 ' Timothy Ware-Hill',
 'Gore Verbinski',
 'Al Campbell',
 ' Alice Mathias',
 'Maïwenn',
 'Richard Weston',
 'Vikramaditya Motwane',
 'Prime Cruz',
 'Andibachtiar Yusuf',
 'Yandy Laurens',
 'Cathy Garcia-Molina',
 'John Mitchell',
 ' Jeremy Kipp Walker',
 'George Clooney',
 'Liu Kuang-hui',
 'Kristian Mercado',
 'Daan Jansen',
 ' Stijn Verlinde',
 'Jay Grace',
 'Paul Dugdale',
 'James Haslam',
 ...]

In [397]:
df.groupby(['director']).size()

director
 Aaron Moorhead              2
 Aaron Woolf                 1
 Abbas Alibhai Burmawalla    1
 Abdullah Al Noor            1
 Abhinav Shiv Tiwari         1
                            ..
Çagan Irmak                  1
Ísold Uggadóttir             1
Óskar Thór Axelsson          1
Ömer Faruk Sorak             2
Şenol Sönmez                 2
Length: 5120, dtype: int64

In [398]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [399]:
#top_direct = df.groupby('director')
#top_direct.head(5)

In [400]:
top_direct = df.groupby('director').size().reset_index(name = 'count').sort_values(by= 'count', ascending=False)
top_direct.head(10)

                 director  count
4020        Rajiv Chilaka     22
4067          Raúl Campos     18
261             Jan Suter     18
4651          Suhas Kadav     16
3235         Marcus Raboy     16
2450            Jay Karas     15
1382  Cathy Garcia-Molina     13
2447          Jay Chapman     12
3306      Martin Scorsese     12
5074      Youssef Chahine     12

In [401]:
top_10 = top_direct.iloc[:10,:]

In [402]:
top_10['director'].unique()

array(['Rajiv Chilaka', 'Raúl Campos', ' Jan Suter', 'Suhas Kadav',
       'Marcus Raboy', 'Jay Karas', 'Cathy Garcia-Molina', 'Jay Chapman',
       'Martin Scorsese', 'Youssef Chahine'], dtype=object)

In [403]:
df = df[df['director'].isin(['Rajiv Chilaka', 'Raúl Campos', ' Jan Suter', 'Suhas Kadav',
       'Marcus Raboy', 'Jay Karas', 'Cathy Garcia-Molina', 'Jay Chapman',
       'Martin Scorsese', 'Youssef Chahine'])]

In [404]:
df = df.reset_index().drop('index', axis=1)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s407,Movie,Chhota Bheem - Neeli Pahaadi,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,+7,64 min,Children & Family Movies,Things get spooky when Bheem and his buddies t...
1,s408,Movie,Chhota Bheem & Ganesh,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2009,+7,68 min,Children & Family Movies,Bheem and Lord Ganesha join forces to save Dho...
2,s409,Movie,Chhota Bheem & Krishna: Mayanagari,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2011,+7,67 min,Children & Family Movies,Young lord Krishna has fallen for demoness Maa...
3,s410,Movie,Chhota Bheem & Krishna: Pataliputra- City of t...,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2010,+7,66 min,Children & Family Movies,Krishna needs Bheem’s help: The ruined city of...
4,s411,Movie,Chhota Bheem And The Broken Amulet,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"July 22, 2021",2013,+7,64 min,Children & Family Movies,When a stranger tries to steal an amulet from ...
...,...,...,...,...,...,...,...,...,...,...,...,...
149,s7514,Movie,Motu Patlu: King of Kings,Suhas Kadav,"Saurav Chakrabarty, Vinay Pathak",India,"July 6, 2017",2016,+7,109 min,"Children & Family Movies, Comedies",Motu and Patlu want to help a circus lion get ...
150,s7821,Movie,Raging Bull,Martin Scorsese,"Robert De Niro, Cathy Moriarty, Joe Pesci, Fra...",United States,"October 1, 2019",1980,+18,129 min,"Classic Movies, Dramas, Sports Movies",This gritty biopic of brutal boxer Jake LaMott...
151,s8273,Movie,The Departed,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...","United States, Hong Kong","January 1, 2021",2006,+18,151 min,"Dramas, Thrillers",Two rookie Boston cops are sent deep undercove...
152,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,"Zina Bethune, Harvey Keitel, Anne Collette, Le...",United States,"July 1, 2019",1967,+18,90 min,"Classic Movies, Dramas, Independent Movies",A woman's revelation that she was once raped s...
153,s8790,Movie,You Changed My Life,Cathy Garcia-Molina,"John Lloyd Cruz, Sarah Geronimo, Rayver Cruz, ...",Philippines,"February 27, 2019",2009,SP,116 min,"Comedies, Dramas, International Movies",Laida and Miggy think they've found perfect ha...

In [405]:
df.to_csv('directors.csv')

 > Hacemos lo mismo con el cast

In [406]:
df_ = df2.copy()

In [407]:
df_['cast']

0                                                     NaN
1       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                     NaN
4       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
                              ...
8802    Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                                  NaN
8804    Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805    Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806    Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
Name: cast, Length: 8807, dtype: object

In [408]:
def separar (col):
    try:
        return col.split(',')
    except:
        pass

In [409]:
df_['cast'] = df_['cast'].apply(separar)

In [410]:
df_['cast']

0                                                    None
1       [Ama Qamata,  Khosi Ngema,  Gail Mabalane,  Th...
2       [Sami Bouajila,  Tracy Gotoas,  Samuel Jouy,  ...
3                                                    None
4       [Mayur More,  Jitendra Kumar,  Ranjan Raj,  Al...
                              ...
8802    [Mark Ruffalo,  Jake Gyllenhaal,  Robert Downe...
8803                                                 None
8804    [Jesse Eisenberg,  Woody Harrelson,  Emma Ston...
8805    [Tim Allen,  Courteney Cox,  Chevy Chase,  Kat...
8806    [Vicky Kaushal,  Sarah-Jane Dias,  Raaghav Cha...
Name: cast, Length: 8807, dtype: object

In [411]:
df_ = df_.explode('cast')

In [412]:
top_cast = df_.groupby('cast').size().reset_index(name = 'count').sort_values(by= 'count', ascending=False)
top_cast.head(22)

                     cast  count
2612          Anupam Kher     39
26941        Rupa Bhimani     31
30303    Takahiro Sakurai     30
15541       Julie Tejwani     28
23624             Om Puri     27
38445      Shah Rukh Khan     26
25410         Rajesh Kava     26
4186          Boman Irani     25
33367           Yuki Kaji     25
1905        Andrea Libman     25
23956        Paresh Rawal     25
32293        Vincent Tong     24
34037        Akshay Kumar     23
14162      Jigna Bhardwaj     23
15656      Junichi Suwabe     21
10150     Fred Tatasciore     21
14589         John Cleese     20
33948        Adam Sandler     20
34168    Amitabh Bachchan     20
16027      Kareena Kapoor     20
22504    Naseeruddin Shah     20
35083  David Attenborough     20

In [413]:
top_22 = top_cast.iloc[:22,].reset_index()
top_22.head()

   index               cast  count
0   2612        Anupam Kher     39
1  26941       Rupa Bhimani     31
2  30303   Takahiro Sakurai     30
3  15541      Julie Tejwani     28
4  23624            Om Puri     27

In [414]:
top_22['count'].sum()

539

In [415]:
top_22['cast'].unique()

array([' Anupam Kher', ' Rupa Bhimani', ' Takahiro Sakurai',
       ' Julie Tejwani', ' Om Puri', 'Shah Rukh Khan', ' Rajesh Kava',
       ' Boman Irani', ' Yuki Kaji', ' Andrea Libman', ' Paresh Rawal',
       ' Vincent Tong', 'Akshay Kumar', ' Jigna Bhardwaj',
       ' Junichi Suwabe', ' Fred Tatasciore', ' John Cleese',
       'Adam Sandler', 'Amitabh Bachchan', ' Kareena Kapoor',
       ' Naseeruddin Shah', 'David Attenborough'], dtype=object)

In [416]:
df_ = df_[df_['cast'].isin([' Anupam Kher', ' Rupa Bhimani', ' Takahiro Sakurai',
       ' Julie Tejwani', ' Om Puri', 'Shah Rukh Khan', ' Rajesh Kava',
       ' Boman Irani', ' Yuki Kaji', ' Andrea Libman', ' Paresh Rawal',
       ' Vincent Tong', 'Akshay Kumar', ' Jigna Bhardwaj',
       ' Junichi Suwabe', ' Fred Tatasciore', ' John Cleese',
       'Adam Sandler', 'Amitabh Bachchan', ' Kareena Kapoor',
       ' Naseeruddin Shah', 'David Attenborough'])]

In [417]:
df_ = df_.reset_index().drop('index', axis=1)
df_

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s28,Movie,Grown Ups,Dennis Dugan,Adam Sandler,United States,"September 20, 2021",2010,+14,103 min,Comedies,Mourning the loss of their beloved junior high...
1,s40,TV Show,Chhota Bheem,NaN,Julie Tejwani,India,"September 16, 2021",2021,+7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
2,s40,TV Show,Chhota Bheem,NaN,Rupa Bhimani,India,"September 16, 2021",2021,+7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
3,s40,TV Show,Chhota Bheem,NaN,Jigna Bhardwaj,India,"September 16, 2021",2021,+7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
4,s40,TV Show,Chhota Bheem,NaN,Rajesh Kava,India,"September 16, 2021",2021,+7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
534,s8675,Movie,Viceroy's House,Gurinder Chadha,Om Puri,"United Kingdom, India, Sweden","December 12, 2017",2017,UR,106 min,Dramas,As viceroy Lord Mountbatten arrives in Delhi t...
535,s8688,Movie,Waarrior Savitri,Param Gill,Om Puri,India,"November 1, 2017",2016,+14,120 min,"Action & Adventure, International Movies, Sci-...","In a modern adaptation of a mythological tale,..."
536,s8771,Movie,Yaadein,Subhash Ghai,Kareena Kapoor,India,"March 1, 2018",2001,+14,171 min,"Dramas, International Movies, Romantic Movies",Two young lovers set out to overcome the obsta...
537,s8773,Movie,Yamla Pagla Deewana 2,Sangeeth Sivan,Anupam Kher,India,"May 1, 2017",2013,+14,147 min,"Action & Adventure, Comedies, International Mo...","Up to his old tricks, con man Dharam poses as ..."
538,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,Adam Sandler,United States,"September 1, 2019",2008,UR,113 min,"Action & Adventure, Comedies",An Israeli counterterrorism soldier with a sec...

In [418]:
df_.to_csv('casting.csv')

 > Hacemos lo mismo con countries

In [419]:
dfc = df2.copy()

In [420]:
def separar (col):
    try:
        return col.split(',')
    except:
        pass

In [421]:
dfc['country'] = dfc['country'].apply(separar)

In [422]:
dfc = dfc.explode('country')

In [423]:
top_country = dfc.groupby('country').size().reset_index(name = 'count').sort_values(by= 'count', ascending=False)
top_country.head(10)

            country  count
191   United States   3211
141           India   1008
190  United Kingdom    628
106   United States    479
122          Canada    271
148           Japan    259
132          France    212
179     South Korea    211
34           France    181
181           Spain    181

In [424]:
dfc = dfc.reset_index().drop('index', axis=1)

In [432]:
dfc

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,+14,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,+18,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,None,"September 24, 2021",2021,+18,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
10845,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,+18,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
10846,s8804,TV Show,Zombie Dumb,NaN,NaN,None,"July 1, 2019",2018,+7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
10847,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,+18,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
10848,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,SP,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
10849,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,+14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [425]:
dfc.to_csv('countries.csv')

In [426]:
top_10c = top_country.iloc[:10,:]
top_10c

            country  count
191   United States   3211
141           India   1008
190  United Kingdom    628
106   United States    479
122          Canada    271
148           Japan    259
132          France    212
179     South Korea    211
34           France    181
181           Spain    181

In [427]:
top_10c['count'].sum()

6641

In [428]:
top_10c['country'].unique()

array(['United States', 'India', 'United Kingdom', ' United States',
       'Canada', 'Japan', 'France', 'South Korea', ' France', 'Spain'],
      dtype=object)

In [429]:
dfc_10 = dfc[dfc['country'].isin(['United States', 'India', 'United Kingdom', ' United States',
       'Canada', 'Japan', 'France', 'South Korea', ' France', 'Spain'])]

In [430]:
dfc_10 = dfc.reset_index().drop('index', axis=1)
dfc_10

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,+14,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,+18,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,None,"September 24, 2021",2021,+18,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,+18,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
10845,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,+18,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
10846,s8804,TV Show,Zombie Dumb,NaN,NaN,None,"July 1, 2019",2018,+7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
10847,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,+18,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
10848,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,SP,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
10849,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,+14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [431]:
dfc.to_csv('countries_10.csv')